#this file is used to automate the deployment of the k8s_lab application in case of any changes in the code or the deployment configuration

---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
    - name: Stop the running container
      command: docker stop django-container
      ignore_errors: yes # Ignore the error if the container is not running already #for the first time deployment
  
    - name: Remove the stopped container
      command: docker rm django-container
    
    - name: Remove the used image
      command: docker rmi django-image

    - name: Build the New Docker image
      command: docker build -t django-image .
    
    - name: Run the Docker container
      command: docker run -d -p 4000:8000 --name django-container django-image  #the 4000 is the port on the host machine and 8000 is the port on the container where the application is running