---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
    - name: Stop the running container
      command: docker stop django-container
      ignore_errors: yes

    - name: Remove the stopped container
      command: docker rm django-container
      ignore_errors: yes
    
    - name: Remove the used image
      command: docker rmi django-image
      ignore_errors: yes

    - name: Build the new Docker image
      command: docker build -t django-image .

    - name: Tag the image with the 'latest' tag
      command: docker tag django-image saaida/my-django-app:latest

    - name: Push the image with the 'latest' tag to Docker Hub
      command: docker push saaida/my-django-app:latest
    
    - name: Run the Docker container
      command: docker run -d -p 4000:8000 --name django-container django-image

    # 4000 is the port on the host machine, and 8000 is the port on the container where the application is running

